### PR TITLE
Abdulmalek javascriptweek4

### PR DESCRIPTION
**Pull request by Abdulmalekhmed**

### CODE REVIEW

**Comment by Erlemorgaine** [comment]
Hi Abdulmalek,

For exercise 1, 2 and 3 your code looks generally good! I did have failing tests for Exercise 4 and 5, so could you have a look at those and fix them?

Some general remarks:
- I also still had some lint and spelling errors when I ran the tests, could you also fix those?
- I think in the README guide it says that you have to remove the comments starting with 'TODO' from the code once you're done, and this will also clean up the files a little. Can you do this for each exercise?

Some exercise-specific remarks:

### Exercise 1

- Good solution, well done! One small thing: I would avoid using abbreviations for variable names (like arrNum), even though I understand why you did it here. When you're working together with other developers, you will want to keep your code as readable as possible, and therefore it's generally better to spell out the entire word (unless it's a very commonly used standard, such as using `i` for an index). 


### Exercise 2

- I really like how you chop up your code in different pieces and the variable names are clear. One very small thing: again for readability, I would suggest to change the name `converToDecimal` to `conversionToDecimal`. When giving variable names, it's best practice to use a 'call to action' - so a word that starts with a verb - for function names, and nouns for variable names.


### Exercise 3

- As asked in the instructions, you gave the sanitizeFruitBasket two parameters. However, you're only using one parameter - could you also use the second parameter? I think in order to be able to use it well, you will also have to rename it from `fruit` to a more specific name, since otherwise the function has two parameters named `fruit` and this becomes a bit confusing. 

As for the tests, the first one is implemented well! The other two need some more work:
- For the test `should not modify the original `fruitBasket` array`, the idea is to check that the function `sanitizeFruitBasket` does not change the original array. However, in order to check this, you actually have to call the function `sanitizeFruitBasket` in the test, for example like this: `sanitizeFruitBasket('lemon')`. 
- The test `should return a new array that does not include the unwanted 'lemon'` is almost correct. The only problem is that in this part `expect(sanitizeFruitBasket)` you're not actually calling the function. So you're not checking if the _result_ of the function doesn't contain 'lemon', but if the function itself doesn't contain 'lemon'. Instead, make sure that you call the function and use the result of the function in `expect(....)`

**Comment by Abdulmalekhmed** [comment]
Hello Erlemorgaine thanks for spending your time to review my homework and thanks also for the useful feedback , about the unit test i use npm test and every thing work I got     9:4  passed there`s no fail or error .

**Comment by bnhoogendijk** [comment]
@Abdulmalekhmed maybe you could have a quick look at the last two bullets of Erle's feedback and see if you can fix your code accordingly? Feel free to reach out to me if you have questions.

**Comment by Abdulmalekhmed** [comment]
hello, bash the last one i dont get it, she said i am not calling the function should i do like 
 expect(sanitizeFruitBasket()).not.toContain('originalFruitBasketContents')?

**Pull request closed without merging**
